import { mkdir, writeFile } from "node:fs/promises";
import { brandScripts } from "../../src/lib/brandScripts.ts";

// Explicit maintainer utility, never a build step or an editor upload endpoint.
// Vendor Google Fonts so static builds and customers do not depend on its API.
const folder = new URL("../../public/fonts/", import.meta.url);
await mkdir(folder, { recursive: true });
const families = [
  { family: "Archivo", spec: "Archivo:ital,wdth,wght@0,62..125,300..800;1,100,500" },
  { family: "IBM Plex Mono", spec: "IBM Plex Mono:wght@400;500" },
  ...[...new Set(brandScripts.slice(1).map(word => word.family))].map(family => ({ family, spec: `${family}:wght@700`, text: brandScripts.filter(word => word.family === family).map(word => word.text).join("") })),
];
const blocks = [];
for (const font of families) {
  const url = new URL("https://fonts.googleapis.com/css2");
  url.searchParams.set("family", font.spec);
  url.searchParams.set("display", "swap");
  if (font.text) url.searchParams.set("text", font.text);
  const response = await fetch(url, { headers: { "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" }, signal: AbortSignal.timeout(30000) });
  if (!response.ok) throw new Error(`Font CSS failed: ${font.family} (${response.status})`);
  let css = await response.text();
  let index = 0;
  for (const match of [...css.matchAll(/url\((https:\/\/[^)]+)\)/g)]) {
    const asset = new URL(match[1]);
    if (asset.hostname !== "fonts.gstatic.com") throw new Error("Unexpected font asset URL");
    const binary = await fetch(asset, { signal: AbortSignal.timeout(30000) });
    if (!binary.ok) throw new Error(`Font asset failed: ${font.family}`);
    const buffer = Buffer.from(await binary.arrayBuffer());
    if (buffer.toString("ascii", 0, 4) !== "wOF2" || buffer.length > 500000) throw new Error("Invalid font response");
    const name = `${font.family.toLowerCase().replaceAll(" ", "-")}-${index++}.woff2`;
    await writeFile(new URL(name, folder), buffer);
    css = css.replace(match[1], `/fonts/${name}`);
  }
  blocks.push(css);
  console.log(`Vendored ${font.family} (${index} faces/subsets)`);
}
await writeFile(new URL("../../src/app/brand-fonts.css", import.meta.url), "/* Generated by tools/design/install-fonts.mjs; licensed font sources in public/fonts. */\n" + blocks.join("\n"));
// Preserve redistributable font licences alongside the vendored binaries.
for (const [name, path] of [["archivo", "ofl/archivo/OFL.txt"], ["ibm-plex-mono", "ofl/ibmplexmono/OFL.txt"], ...families.slice(2).map(font => [font.family.toLowerCase().replaceAll(" ", "-"), `ofl/${font.family.toLowerCase().replaceAll(" ", "")}/OFL.txt`])]) {
  const response = await fetch(`https://raw.githubusercontent.com/google/fonts/main/${path}`, { signal: AbortSignal.timeout(30000) });
  if (!response.ok) throw new Error(`Licence fetch failed: ${name}`);
  await writeFile(new URL(`${name}-OFL.txt`, folder), await response.text());
}
